### ISSUE TITLE
BOM and layer count

### ISSUE THREAD

**Issue by thomasfla** [DieBieEngineering/DieBieSlave#1]
Hi, thanks for this board, I think it will be very usefully for many project!

I'm considering building a couple of boards..
Do you have a BOM ready for the non-Altium users? 

Also, looking at the gerber, it looks like it's a 6 layers board. Is it right? Do we really need 6 layers for this project or do you think it's doable on 4 layer with similar ? (or even 2?)

Best,
T.

**Comment by DieBieEngineering** [comment]
Hi Thomas!

Thanks for your interest in the project. You can see all data with the free
Altium viewer license. The production data should be available in the repo
as well, either in releases or in the project output folder.

With this small size I am afraid that 6 layer is your only option.

Thanks ,
Danny
