### ISSUE TITLE
LAN9252 configuration

### ISSUE THREAD

**Issue by FCam1** [DieBieEngineering/DieBieSlave#4]
Hi,
We have built a board and it seems to work ! For the moment I did some tests with the  [SOEM library](https://github.com/OpenEtherCATsociety/SOEM) and the device is recognized as a slave.

As I understand the LAN9252 have to be configured through ethercat, for that you give an [DieBieSlave-IMU.esx](https://github.com/DieBieEngineering/DieBieSlave-Firmware-IMU/tree/master/ESIEtherCAT) and it has to be opened with [ethercat-SDK](https://rt-labs.com/refman/ethercat-sdk/slaveeditor.php) in order to generate a binary. This binary can be sent to the LAN9252 with this [eepromtool](https://github.com/OpenEtherCATsociety/SOEM/tree/master/test/linux/eepromtool), for example. Am I right ? 
Another point : I can't generate the binary file in ethercat-SDK with the free licence. Did you buy the licence?

Thanks

**Comment by DieBieEngineering** [comment]
Dear Florenc,

Thanks for your email! Sounds good!

Yes I use twincat and the xml file to configure/write the eeprom data to
the slave. The xml and esc are made with the tool provided by rt-labs, back
then the tool was free and allowed for the generation of this section and
description. I am not up to speed with the current status and whether it is
still free.......

Op di 3 sep. 2019 om 10:33 schreef Florenc Caminade <
notifications@github.com>:

**Comment by FCam1** [comment]
It's ok, I succeded to configure the device and now it is reconized as a slave in twincat
